### PR TITLE
Added the ability for reviews to also be added

### PR DESCRIPTION
**Pull request by Thoride-Dev**
Previously did not add any reviews made on must to the letterboxd csv. Now it can via the letterboxd review format.

### CODE REVIEW

**Comment by findmeplease1** [comment]
how dis works? С чего начать то вообще?

**Comment by Thoride-Dev** [comment]
> how dis works? С чего начать то вообще?

@findmeplease1 are you asking about:
1. how to use the exporter?
or
2. how do my changes to the exporter work?

**Comment by iterlace** [comment]
Thanks for your contribution. I've done a little refactoring so it's ready to be merged.

**Comment by findmeplease1** [comment]
> > how dis works? С чего начать то вообще?
> 
> @findmeplease1 are you asking about:
> 
> 1. how to use the exporter?
>    or
> 2. how do my changes to the exporter work?

Я не очень понимаю как это выгрузить в IDE 
Так же при запуске напрямую на гитхабе - выдает ошибку

**Comment by findmeplease1** [comment]
image

**Comment by iterlace** [comment]
> image

Fixed.

**Pull request merged**
